// Generated by CoffeeScript 1.6.2
(function () {
    define(["core/controller"], function (BaseController) {
        "use strict";
        var Controller, LeadController;

        Controller = {
            modelName: "lead"
        };
        LeadController = Marionette.Controller.extend(Controller);
        _.extend(LeadController.prototype, new BaseController());
        return LeadController;
    });

}).call(this);
