imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trusted_proxies: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:
        cookie_lifetime:   3600
    translator:      { fallback: en }


fos_user:
    db_driver:     orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class:    Btn\UserBundle\Entity\User
    from_email:
        address:        noreply@bitnoise.pl
        sender_name:    Btn App

fos_oauth_server:
    db_driver: orm
    client_class:        Btn\ApiBundle\Entity\Client
    access_token_class:  Btn\ApiBundle\Entity\AccessToken
    refresh_token_class: Btn\ApiBundle\Entity\RefreshToken
    auth_code_class:     Btn\ApiBundle\Entity\AuthCode
    service:
        user_provider: fos_user.user_manager

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ BtnCrudBundle ]
    #java: /usr/bin/java
    filters:
        lessphp:
            file:   %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
    assets:
        app_js:
            inputs:
                - js/require.js
                - js/require-init.js
        app_css:
            inputs:
                - ../vendor/twbs/bootstrap/less/bootstrap.less
                - less/style.less
                - js/vendors/datepicker/css/datepicker.css

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# raul_fraile_ladybug:
#     general:
#         expanded:             false
#     object:
#         max_nesting_level:    4

#knp paginator fix
knp_paginator:
    default_options:
        distinct: false

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

services:
    btn.lead_manager:
        class: Btn\AppBundle\Model\LeadManager
        scope: request
        arguments:
            em:          '@doctrine.orm.entity_manager'
            paginator:   '@knp_paginator'
            twig:        '@twig'
            formFactory: '@form.factory'
    btn.time_manager:
        class: Btn\AppBundle\Model\TimeManager
        scope: request
        arguments:
            em:          '@doctrine.orm.entity_manager'
            paginator:   '@knp_paginator'
            twig:        '@twig'
            formFactory: '@form.factory'
    btn.listener.preexecute:
        class: Btn\AppBundle\Listener\PreExecute
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
        priority: -1000
        arguments:
            resolver: "@controller_resolver"
    btn.user_manager:
        class: Btn\AppBundle\Model\UserManager
        scope: request
        arguments:
            em:          '@doctrine.orm.entity_manager'
            paginator:   '@knp_paginator'
            twig:        '@twig'
            formFactory: '@form.factory'