# app/config/security.yml
security:
    providers:
        custom:
            id: btn_user.btn_user_provider
        fos_userbundle:
            id: fos_user.user_manager

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider:      custom
                csrf_provider: form.csrf_provider
                always_use_default_target_path: true
                default_target_path: /
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/css,         role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/js,          role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$,      role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,            role: IS_AUTHENTICATED_REMEMBERED }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN