<?php

namespace Btn\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends EntityRepository
{

    /**
     * Find project suggestions
     *
     * @param  string $query
     * @return array $projects
     **/
    public function findSuggestions($query)
    {
        $qb = $this->createQueryBuilder('p');

        $projects = $qb->add('select',  'p')
           ->add('where',   'p.name LIKE :query')
           ->add('orderBy', 'p.name ASC')
           ->setParameter(':query', $query . '%')
           ->getQuery()
           ->getResult()
        ;

        $results = array();
        foreach ($projects as $project) {
            $results[] = $project->getName();
        }

        return $results;
    }
}
