// Generated by CoffeeScript 1.6.2
/* global Backbone, Marionette, define, _, Moderniz
 */

(function () {
    "use strict";
    define(["application/config"], function (config) {
        var App;

        App = new Marionette.Application();
        App.url = {
            api : "/btntt/web/api/",
            rest: "/btntt/web/rest/"
        };
        App.initializeLayout = function () {
            var _this = this;

            require(["views/layout/main"], function (LayoutView) {
                _this.layoutView = new LayoutView();
            });
            return this;
        };
        App.setUrls = function () {
            var url;

            for (url in this.url) {
                this.updateUrl(url);
            }
            return this;
        };
        App.updateUrl = function (url) {
            this.url[url] = Backbone.history.location.origin + this.url[url];
            return url;
        };
        App.getUrl = function (type, route) {
            return this.url[type] + route;
        };
        App.initApp = function () {
            $.get(this.url.api + "get/init-data/", _.bind(this.onInitData, this));
            return this;
        };
        App.onInitData = function (response) {
            var initData;

            initData = JSON.parse(response);
            if (!initData.user.auth) {
                return window.location = initData.baseUrl + "/login";
            } else {
                this.userData = initData.user;
                this.setUrls();
                require(["application/router"], function (router) {
                    router.initialize();
                    return router;
                });
                return this;
            }
        };
        App.addRegions({
            content  : "#content",
            paginator: "#paginator"
        });
        App.scrollTop = function () {
            if (Modernizr.touch && !window.location.hash) {
                return $(window).load(function () {
                    return setTimeout((function () {
                        if ($(window).scrollTop() < 20) {
                            return window.scrollTo(0, 1);
                        }
                    }), 0);
                });
            }
        };
        App.addInitializer(function () {
            this.initApp();
            this.scrollTop();
            return this;
        });
        return App;
    });

}).call(this);
