// Generated by CoffeeScript 1.6.2
(function() {
  var initialize;

  define(["controllers/lead", "controllers/enquiry"], function(LeadController, EnquiryController) {
    "use strict";
    var EnquiryRouter, LeadRouter;

    LeadRouter = Marionette.AppRouter.extend({
      appRoutes: {
        leads: "show"
      }
    });
    return EnquiryRouter = Marionette.AppRouter.extend({
      appRoutes: {
        enquiries: "show"
      }
    });
  });

  initialize = function() {
    var enquiryRouter, leadRouter;

    leadRouter = new LeadRouter({
      controller: new LeadController()
    });
    enquiryRouter = new EnquiryRouter({
      controller: new EnquiryController()
    });
    return Backbone.history.start();
  };

  ({
    initialize: initialize
  });

}).call(this);
