// Generated by CoffeeScript 1.6.2
(function () {
    define(["controllers/lead", "controllers/enquiry"], function (LeadController, EnquiryController) {
        "use strict";
        var EnquiryRouter, LeadRouter, enquiryRoutes, initialize, leadRoutes;

        leadRoutes = {
            appRoutes: {
                leads: "show"
            }
        };
        enquiryRoutes = {
            appRoutes: {
                enquiries: "show"
            }
        };
        LeadRouter = Marionette.AppRouter.extend(leadRoutes);
        EnquiryRouter = Marionette.AppRouter.extend(enquiryRoutes);
        initialize = function () {
            var enquiryRouter, leadRouter;

            leadRouter = new LeadRouter({
                controller: new LeadController()
            });
            enquiryRouter = new EnquiryRouter({
                controller: new EnquiryController()
            });
            Backbone.history.start();
            return this;
        };
        return {
            initialize: initialize
        };
    });

}).call(this);
