// Generated by CoffeeScript 1.6.2
/* global define, Backbone
*/


(function() {
  "use strict";  define([], function() {
    var Collection, PaginatedCollection;

    Collection = {
      options: null,
      model: null,
      initialize: function(collection) {
        this.model = collection.model;
        this.paginator_core.url = collection.url;
        return this;
      },
      paginator_core: {
        type: "GET",
        dataType: "json",
        url: ""
      },
      paginator_ui: {
        firstPage: 1,
        currentPage: 1,
        perPage: 3,
        totalPages: 10,
        pagesInRange: 3
      },
      server_api: {
        $filter: true,
        $top: function() {
          return this.totalPages * this.perPage;
        },
        $skip: function() {
          return this.totalPages * this.perPage;
        },
        orderby: "id",
        $format: "json"
      },
      parse: function(response) {
        return response;
      }
    };
    PaginatedCollection = Backbone.Paginator.requestPager.extend(Collection);
    return PaginatedCollection;
  });

}).call(this);
