// Generated by CoffeeScript 1.6.2
/* global define, Backbone
 */

(function () {
    "use strict";
    define([], function () {
        var Collection, PaginatedCollection;

        Collection = {
            options       : null,
            model         : null,
            initialize    : function (options) {
                this.model = options.collection.model;
                this.paginator_core.url = options.url.api + 'paginate/' + options.modelName;
                return this;
            },
            paginator_core: {
                type    : "GET",
                dataType: "json",
                url     : ""
            },
            paginator_ui  : {
                firstPage   : 1,
                currentPage : 1,
                pagesInRange: 1,
                perPage     : 1,
                totalPages  : 1
            },
            server_api    : {
                $filter: true,
                $top   : function () {
                    return this.totalPages * this.perPage;
                },
                $skip  : function () {
                    return this.totalPages * this.perPage;
                },
                orderby: "id",
                $format: "json"
            },
            parse         : function (response) {
                console.log(response);
                this.totalPages = response.total;
                this.perPage = response.perPage;
                return response;
            }
        };
        PaginatedCollection = Backbone.Paginator.requestPager.extend(Collection);
        return PaginatedCollection;
    });

}).call(this);
